name: strategy
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  multiple_result: ^5.2.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.9.0
  lints: ^5.0.0
  mockito: ^5.5.1
  test: ^1.24.0
